# Generated by Django 4.0.4 on 2022-05-03 04:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import translators.models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=125, verbose_name='نام')),
                ('last_name', models.CharField(max_length=125, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(upload_to=utils.get_file_path)),
            ],
            options={
                'verbose_name': 'مترجم',
                'verbose_name_plural': 'مترجمان',
            },
        ),
        migrations.CreateModel(
            name='QuranTranslateAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('audio', models.FileField(upload_to=translators.models.get_audio_path, verbose_name='صوت')),
                ('text', models.TextField()),
                ('ayeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_qari', to='translators.ayeh', verbose_name='آیه')),
                ('qari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translators.translator', verbose_name='قاری')),
            ],
            options={
                'verbose_name': 'صوت قرآن',
                'verbose_name_plural': 'صوت های قرآن',
            },
        ),
    ]
