# Generated by Django 4.0.4 on 2022-05-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
        ('translators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurantranslateaudio',
            name='ayeh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_qari', to='quran.ayeh', verbose_name='آیه'),
        ),
        migrations.DeleteModel(
            name='Ayeh',
        ),
    ]
