# Generated by Django 4.0.4 on 2022-05-03 21:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sureh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=250)),
                ('publish', models.CharField(choices=[('مکی', 'مکی'), ('مدینه', 'مدینه')], max_length=10)),
                ('meaning', models.CharField(max_length=250)),
                ('nozol', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'سوره ها',
            },
        ),
        migrations.CreateModel(
            name='Ayeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField(verbose_name='متن')),
                ('translate', models.TextField(verbose_name='ترجمه')),
                ('sejdeh', models.CharField(choices=[('مستحب', 'مستحب'), ('واجب', 'واجب'), ('ندارد', 'ندارد')], max_length=6, verbose_name='سجده')),
                ('hezb', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=10, verbose_name='حزب')),
                ('joze', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24), ('25', 25), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30)], max_length=10, verbose_name='جز')),
                ('page_number', models.PositiveIntegerField(verbose_name='شماره صفحه')),
                ('ayeh_number', models.PositiveIntegerField(verbose_name='شماره آیه')),
                ('sureh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.sureh', verbose_name='سوره')),
            ],
            options={
                'verbose_name': 'ایه',
                'verbose_name_plural': 'آیه ها',
            },
        ),
    ]
