# Generated by Django 4.0.4 on 2022-05-02 22:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praiseres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dirge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dirge_name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to=utils.get_file_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirges', to='dirges.dirgecategory')),
                ('praiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirges', to='praiseres.praiser')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
