# Generated by Django 4.0.4 on 2022-05-02 23:28

from django.db import migrations, models

import utils


class Migration(migrations.Migration):

    dependencies = [
        ('dirges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirge',
            name='logo',
            field=models.ImageField(blank=True, upload_to=utils.get_file_path),
        ),
        migrations.AddField(
            model_name='dirgecategory',
            name='logo',
            field=models.ImageField(blank=True, upload_to=utils.get_file_path),
        ),
    ]
