# Generated by Django 4.0.4 on 2022-05-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praiseres', '0001_initial'),
        ('dirges', '0002_dirge_logo_dirgecategory_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirge',
            old_name='dirge_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dirge',
            name='praiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dirges', to='praiseres.praiser'),
        ),
    ]
