# Generated by Django 4.0.4 on 2022-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfacilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolschedule',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه')], max_length=10),
        ),
    ]
