# Generated by Django 4.0.4 on 2022-05-03 21:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=125, verbose_name='نام')),
                ('last_name', models.CharField(max_length=125, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(blank=True, upload_to=utils.get_file_path)),
            ],
            options={
                'verbose_name': 'قاری',
                'verbose_name_plural': 'قاریان',
            },
        ),
        migrations.CreateModel(
            name='QuranAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('audio', models.FileField(upload_to=utils.get_file_path, verbose_name='صوت')),
                ('ayeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elyas', to='quran.ayeh', verbose_name='آیه')),
                ('qari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qari.qari', verbose_name='قاری')),
            ],
            options={
                'verbose_name': 'صوت قرآن',
                'verbose_name_plural': 'صوت های قرآن',
            },
        ),
    ]
